[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1716: Identifiers should not match keywords", Justification = "this is default name created by AWS", Scope = "type", Target = "DotNet5.Function")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1304: Specify CultureInfo", Justification = "the default culture is okay")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1305: Specify IFormatProvider", Justification = "the default format is okay")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1307: Specify StringComparison for clarity", Justification = "the default format is okay")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1822: Mark members as static", Justification = "this is default method created by AWS", Scope = "type", Target = "DotNet5.Function")]
